### PR TITLE
Add basic support for native Promises

### LINKED ISSUE #11: Add support for Promises
Hi there, it would be awesome if this module supported Promises as well as traditional Node callbacks. This is actually something I would love to tackle myself and submit a PR for if that's okay with you!

### PR DESCRIPTION
**Pull request by oksas**
This is my stab at implementing Promises so that this module supports both Node-style callbacks and Promises. Here's a rundown of the changes:

- `es6` env added to eslint config, otherwise eslint would complain that `Promise` was not defined. If you are opposed to this, another option would be to add `Promise` to the `globals` section in the eslint config.
- The `thumb` method returns a `new Promise`, wraps everything inside that Promise, and the Promise's `resolve` and `reject` get passed down the chain so that whenever `done`/`callback` are used, `resolve` and `reject` are in scope so they can be used instead if the user is using Promises instead of a callback.
- If there is an error with user input, the `err` passed to the callback (or to `reject`) is now an actual `Error` object instead of just a string. I'm not super experienced handling errors but this seemed like a good way to do it based on the information I could find (like from [here](https://www.joyent.com/node-js/production/design/errors)).

Let me know how that looks! Definitely open to feedback here, and I'm not 100% about everything. I think this might be a good stage to add some simple tests to the module, to always ensure both callbacks and Promises work, reject with errors at the right time with insufficient or invalid input, etc. I have a small ugly script I have been using to test this stuff myself but it might be worth adding some tests to the module itself.

Closes #11

### CODE REVIEW

**Comment by oksas** [comment]
O silly me, didn't see that you did actually add unit tests. I will look into the failing test here then and fix that.

**Comment by honza** [comment]
At first glance, this looks good. I'll pull down the changes later, and take it for a spin. Thanks for submitting this!

**Comment by oksas** [comment]
Sounds great, thanks dude!

**Comment by honza** [comment]
Running `./bin/thumb` without any arguments throws this error:

```
(node:28912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: options.logger is not a function
```

Other than that, works great!

**Comment by oksas** [comment]
Hmm ok, glad you tested the CLI because I clearly did not. I'll look into it this afternoon and refine. Thanks man!

**Comment by oksas** [comment]
It should be all good to go now. I ran my usual tests for ensuring the module works still with both callbacks and Promises, and the command line interface also seems to work without issue. Let me know how it looks!

**Comment by honza** [comment]
Very good, thanks ✨

**Pull request merged**
